//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStore
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoStoreEntities : DbContext
    {
        private static AutoStoreEntities context;

        public AutoStoreEntities()
            : base("name=AutoStoreEntities")
        {
        }

        public static AutoStoreEntities GetContext()
        {
            if (context == null)
                context = new AutoStoreEntities();

            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
